cookie:
  expiry_days: 1
  key: some_signature_key_hello_world # Must be a string
  name: cookie_monster_name_is_chris
credentials: 
  usernames:
    dporter:
      email: daniel.porter@cegedimrx.co.uk
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Daniel Porter
      password: $2b$12$JqHlJBZd1w5s0iEYLPKczeYKfaM/i7qqRA.4NzqSfMJCa501zrlHm # Will be hashed automatically
      roles:
      - admin
      - editor
      - viewer
    cegedim:
      email: guest@guest.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Cegedim
      password: $2b$12$ouL6FrX71ICp7UWbocESTO/n/diw/JOmE5nz4Gfi6vvlduS5b/qy. # Will be hashed automatically
      roles:
      - viewer
oauth2:
  google: # Follow instructions: https://developers.google.com/identity/protocols/oauth2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
  microsoft: # Follow instructions: https://learn.microsoft.com/en-us/graph/auth-register-app-v2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
    tenant_id: # To be filled
pre-authorized:
  emails:
