cookie:
  expiry_days: 1
  key: some_signature_key_hello_world234234jskfskfs_po(ewer%^%$$___bin
  name: cookie_monster_name_is_chris
credentials:
  usernames:
    cegedim:
      email: guest@guest.com
      failed_login_attempts: 0
      logged_in: false
      name: Cegedim
      password: $2b$12$ouL6FrX71ICp7UWbocESTO/n/diw/JOmE5nz4Gfi6vvlduS5b/qy.
      roles:
      - viewer
    dporter:
      email: daniel.porter@cegedimrx.co.uk
      failed_login_attempts: 0
      logged_in: false
      name: Daniel Porter
      password: $2b$12$JqHlJBZd1w5s0iEYLPKczeYKfaM/i7qqRA.4NzqSfMJCa501zrlHm
      roles:
      - admin
      - editor
      - viewer
    josh:
      email: josh@josh
      failed_login_attempts: 0
      logged_in: false
      name: Josh
      password: $2b$12$t.D6ZZ3d16JhreWypSRyOOII.r6Mbri5zs.NOExSzlznps8GuyYG6
      roles:
      - viewer
    kieran:
      email: kieran@kieran
      failed_login_attempts: 0
      logged_in: false
      name: Kieran Fee
      password: test
      roles:
      - viewer
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails: 
    - test@test.com
